/** Metadata parsed from a blog post's YAML front matter. */
export interface PostMeta {
  /** URL-safe identifier derived from the filename. */
  slug: string;
  /** Post title. */
  title: string;
  /** ISO-8601 date string (YYYY-MM-DD). */
  date: string;
  /** Author name. */
  author: string;
  /** Whether the post was generated by AI. */
  aiGenerated: boolean;
  /** Categorisation labels. */
  tags: string[];
  /** Path to hero image (relative to public/). */
  heroImage: string;
  /** One-sentence preview for the blog index. */
  summary: string;
}

/** A full blog post: metadata + rendered HTML body. */
export interface Post extends PostMeta {
  /** Markdown body rendered to an HTML string. */
  contentHtml: string;
}
