import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";

import { getAllSlugs, getPostBySlug } from "@/lib/blog";

interface BlogPostPageProps {
  params: Promise<{ slug: string }>;
}

export function generateStaticParams(): { slug: string }[] {
  return getAllSlugs().map((slug) => ({ slug }));
}

export default async function BlogPostPage({ params }: BlogPostPageProps) {
  const { slug } = await params;
  const post = await getPostBySlug(slug);

  if (!post) {
    notFound();
  }

  return (
    <section className="page blog-post">
      <Link className="blog-back-link" href="/blog">
        &larr; Back to blog
      </Link>

      {/* ── Hero image ── */}
      <div className="blog-hero-image">
        <Image
          alt={post.title}
          height={400}
          priority
          src={post.heroImage}
          width={800}
        />
      </div>

      {/* ── Header ── */}
      <header className="blog-post-header">
        <div className="blog-card-badges">
          <span className="label">{post.date}</span>
          {post.aiGenerated && (
            <span className="badge-ai">AI-Generated</span>
          )}
        </div>
        <h1>{post.title}</h1>
        <p className="blog-post-author">By {post.author}</p>
        <div className="blog-phoenix-brand">
          <Image
            alt="Phoenix Agentic Engine"
            className="blog-phoenix-logo"
            height={20}
            src="/images/phoenix-icon.png"
            width={20}
          />
          <span>Phoenix Agentic Engine</span>
        </div>
      </header>

      {/* ── AI disclaimer ── */}
      {post.aiGenerated && (
        <div className="blog-disclaimer">
          <strong>Automated post</strong> — This post was automatically
          generated by AI from engine activity data. It has been reviewed but
          may contain inaccuracies. For authoritative information, see the
          linked PRs and commits.
        </div>
      )}

      {/* ── Body ── */}
      <article
        className="blog-body"
        dangerouslySetInnerHTML={{ __html: post.contentHtml }}
      />

      {/* ── Footer nav ── */}
      <div className="blog-post-footer">
        <Link className="button" href="/blog">
          &larr; All posts
        </Link>
      </div>
    </section>
  );
}
